// <auto-generated />
namespace Universal.DataCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_project_flow_node_last_update_time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_project_flow_node_last_update_time));
        
        string IMigrationMetadata.Id
        {
            get { return "201704100827599_add_project_flow_node_last_update_time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
