// <auto-generated />
namespace Universal.DataCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_pro_plan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_pro_plan));
        
        string IMigrationMetadata.Id
        {
            get { return "201701060642399_edit_pro_plan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
