// <auto-generated />
namespace Universal.DataCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_project_flow_pidds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_project_flow_pidds));
        
        string IMigrationMetadata.Id
        {
            get { return "201702210821070_remove_project_flow_pidds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
