// <auto-generated />
namespace Universal.DataCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_flow_node_compact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_flow_node_compact));
        
        string IMigrationMetadata.Id
        {
            get { return "201703030320056_add_flow_node_compact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
