// <auto-generated />
namespace Universal.DataCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_flow_node_frist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_flow_node_frist));
        
        string IMigrationMetadata.Id
        {
            get { return "201706030353274_add_flow_node_frist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
